per_page: "10"
users:
  ava_size: "100x100"
  default_avatar: "default.png"
admin:
  book_size: "100x100"
  book_large_edit: "400x490"
per_page: 5
books:
  per_page: 8
  book_size: "190x250"
  book_size_large: "300x400"
  default_book: "/assets/nhagiakim.jpg"

per_page: 4
