per_page: "10"
review_per_page: "2"
users:
  ava_size: "100x100"
  comment_ava: "50x50"
  default_avatar: "default.png"
admin:
  book_size: "100x100"
  book_large_edit: "400x490"
books:
  per_page: 8
  book_size: "190x250"
  book_size_large: "300x400"
  default_book: "/assets/default.jpg"
status: 2
activity:
  trackable:
    relationship:
      content: "has new relationship"
